from __future__ import annotations

LOCALIZATION_DICT = {
    "es": {
        "app_title": "TraderExpert",
        "start": "Iniciar",
        "pause": "Pausar",
        "stop": "Detener",
        "analyze": "Analizar",
        "settings": "Configuración",
        "virtual_balance": "Saldo virtual",
        "active_asset": "Activo",
        "wins": "Ganadas",
        "losses": "Perdidas",
        "confidence": "Confianza",
        "engine_state": "Estado del Motor",
        "risks_detected": "Riesgos detectados",
        "external_context": "Contexto externo",
        "date": "Fecha",
        "asset": "Activo",
        "signal": "Señal",
        "status": "Estado",
        "conf": "Conf.",
        "reason": "Razón del análisis",
        "delta": "Delta",
        "page_info": "Página {page} de {total}",
        "no_signals": "No hay señales registradas",
        "no_signals_desc": "Las señales aparecerán aquí automáticamente una vez que inicies el análisis de mercado.",
        "confirm_title": "Confirmar",
        "confirm_text": "¿Estás seguro de realizar esta acción?",
        "cancel": "Cancelar",
        "confirm": "Confirmar",
        "reset_balance_tip": "Restablecer balance virtual",
        "clear_history_tip": "Limpiar historial de señales",
        "export_csv_tip": "Exportar historial a CSV",
        "mt5_connected": "Conectado",
        "mt5_disconnected": "Desconectado",
        "scanning": "Escaneando mercado...",
        "scanning_btn": "ESCANEANDO...",
        "state_running": "Activo",
        "state_stopped": "Detenido",
        "dir_wait": "ESPERAR",
        "dir_up": "SUBE",
        "dir_down": "BAJA",
        "no_risks": "Sin riesgos detectados.",
        "no_news": "No hay noticias relevantes en este momento.",
        "waiting_login": "Esperando inicio de sesion.",
        "mt5_not_connected": "MetaTrader 5 no conectado.",
        "analysis_in_progress": "Análisis en curso...",
        "reset_balance_confirm_text": "¿Estás seguro de que deseas restablecer el saldo virtual al valor inicial?",
        "clear_history_confirm_text": "¿Estás seguro de que deseas eliminar permanentemente todo el historial de señales?",
        "minimize_aria": "Minimizar",
        "fullscreen_aria": "Pantalla Completa",
        "quit_aria": "Salir",
        "entry_label": "Entrada",
        "exit_label": "Salida",
        "sources_connected_format": "{0} fuentes conectadas",
        "news_processed_format": "{1} eventos/noticias procesados",
        "seeking_market_events": "Buscando eventos de mercado...",
        
        # Settings page specific
        "step1_title": "Conexión",
        "step2_title": "Mercado",
        "step3_title": "Simulación",
        "step4_title": "Estrategia",
        "config_title": "Configuración de TraderExpert",
        "save": "Guardar e Iniciar",
        "next": "Siguiente",
        "prev": "Anterior",
        "back_home": "Volver al Inicio",
        "step1_header": "Terminal MT5",
        "step2_header": "Configuración de Mercado",
        "step3_header": "Parámetros y Sonido",
        "step4_header": "Estrategia e Inteligencia (RAG)",
        "field_mt5_path": "Ruta MT5 (Opcional)",
        "field_mt5_account": "Cuenta",
        "field_mt5_password": "Contraseña",
        "field_mt5_server": "Servidor",
        "field_market_type": "Tipo de mercado",
        "field_active_symbol": "Activo (Símbolo)",
        "field_timeframe": "Temporalidad",
        "field_chart_type": "Tipo de Gráfico",
        "field_virtual_balance": "Capital Virtual",
        "field_stake_amount": "Monto por Señal",
        "field_payout_percent": "Payout %",
        "field_confidence_threshold": "Confianza Mínima",
        "field_prediction_horizon": "Horizonte Predicción (min)",
        "field_analysis_interval": "Intervalo Análisis (min)",
        "field_enable_sounds": "Sonidos de Alerta",
        "field_strategy_prompt": "Instrucciones de Estrategia (Prompt)",
        "field_rag_directory": "Carpeta de Conocimiento (RAG)",
        "field_lang_response": "Idioma de la App",
        "field_enable_rag": "Uso de RAG / Entrenamiento",
        "sounds_enabled": "🔊 Activado",
        "sounds_disabled": "🔇 Desactivado",
        "rag_enabled": "✅ Activado",
        "rag_disabled": "❌ Desactivado",
        "market_forex": "🌐 Forex",
        "market_indices": "📊 Índices",
        "market_commodities": "🥇 Commodities",
        "market_crypto": "₿ Cripto",
        "market_acciones": "🏢 Acciones",
        "chart_candles": "🕯️ Velas",
        "chart_line": "📈 Línea",
        "chart_bars": "📊 Barras",
        
        "balance_reset_success": "Balance restablecido correctamente",
        "history_cleared_success": "Historial eliminado",
        "export_success": "Historial exportado con éxito",
        "export_error": "Error al exportar",
        "connection_error": "Error de conexión",

        # Step 5: AI Provider
        "step5_title": "Inteligencia Artificial",
        "step5_header": "Proveedor de IA",
        "field_ai_provider": "Proveedor de IA",
        "field_ai_api_key": "API Key",
        "field_ai_model": "Modelo",
        "field_ai_endpoint": "URL",
        "field_ai_api_version": "Versión API",
        "btn_test_connection": "Probar Conexión",
        "test_success": "✅ Conexión exitosa",
        "test_fail": "❌ Error de conexión",
        "testing": "Probando...",
        "ai_key_placeholder": "sk-... o tu API Key",
        "ai_endpoint_placeholder": "https://tu-recurso.openai.azure.com/...",
        
        "trading_mode_label": "Modo de Operación",
        "mode_simulation": "🎮 Simulación",
        "mode_real": "💰 Cuenta Real",
        "real_mode_warning": "⚠️ Operar en modo real implica riesgo de pérdida de capital",
        "field_lot_size": "Volumen",
        "field_sl_multiplier": "SL (ATR ×)",
        "field_tp_ratio": "TP Ratio (R:R)",
        "equity_label": "Equity Real",
        "real_balance": "Saldo Real",
        "market_open": "Mercado Abierto",
        "market_closed": "Mercado Cerrado",
        "next_analysis_in": "Siguiente análisis en",
        "next_analysis": "Próximo análisis",
        "analyzing": "Analizando...",
    },
    "en": {
        "app_title": "TraderExpert",
        "start": "Start",
        "pause": "Pause",
        "stop": "Stop",
        "analyze": "Analyze",
        "settings": "Settings",
        "virtual_balance": "Virtual Balance",
        "active_asset": "Asset",
        "wins": "Wins",
        "losses": "Losses",
        "confidence": "Confidence",
        "engine_state": "Engine State",
        "risks_detected": "Detected Risks",
        "external_context": "External Context",
        "date": "Date",
        "asset": "Asset",
        "signal": "Signal",
        "status": "Status",
        "conf": "Conf.",
        "reason": "Analysis Reason",
        "delta": "Delta",
        "page_info": "Page {page} of {total}",
        "no_signals": "No signals recorded",
        "no_signals_desc": "Signals will appear here automatically once you start market analysis.",
        "confirm_title": "Confirm",
        "confirm_text": "Are you sure you want to perform this action?",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "reset_balance_tip": "Reset virtual balance",
        "clear_history_tip": "Clear signal history",
        "export_csv_tip": "Export history to CSV",
        "mt5_connected": "Connected",
        "mt5_disconnected": "Disconnected",
        "scanning": "Scanning market...",
        "scanning_btn": "SCANNING...",
        "state_running": "Running",
        "state_stopped": "Stopped",
        "dir_wait": "WAIT",
        "dir_up": "UP",
        "dir_down": "DOWN",
        "no_risks": "No risks detected.",
        "no_news": "No relevant news at this time.",
        "waiting_login": "Waiting for login.",
        "mt5_not_connected": "MetaTrader 5 not connected.",
        "analysis_in_progress": "Analysis in progress...",
        "reset_balance_confirm_text": "Are you sure you want to reset the virtual balance to the initial value?",
        "clear_history_confirm_text": "Are you sure you want to permanently delete all signal history?",
        "minimize_aria": "Minimize",
        "fullscreen_aria": "Full Screen",
        "quit_aria": "Quit",
        "entry_label": "Entry",
        "exit_label": "Exit",
        "sources_connected_format": "{0} sources connected",
        "news_processed_format": "{1} events/news processed",
        "seeking_market_events": "Searching for market events...",
        
        # Settings page specific
        "step1_title": "Connection",
        "step2_title": "Market",
        "step3_title": "Simulation",
        "step4_title": "Strategy",
        "config_title": "TraderExpert Settings",
        "save": "Save Settings",
        "next": "Next",
        "prev": "Previous",
        "back_home": "Back to Home",
        "step1_header": "MetaTrader 5 Setup",
        "step2_header": "Market Settings",
        "step3_header": "Parameters & Sound",
        "step4_header": "Strategy & Intelligence (RAG)",
        "field_mt5_path": "Path to terminal64.exe",
        "field_mt5_account": "Account",
        "field_mt5_password": "Password",
        "field_mt5_server": "Server",
        "field_market_type": "Market Type",
        "field_active_symbol": "Asset (Symbol)",
        "field_timeframe": "Timeframe",
        "field_chart_type": "Chart Type",
        "field_virtual_balance": "Virtual Capital",
        "field_stake_amount": "Amount per Signal",
        "field_payout_percent": "Payout %",
        "field_confidence_threshold": "Min Confidence",
        "field_prediction_horizon": "Prediction Horizon (min)",
        "field_analysis_interval": "Analysis Interval (min)",
        "field_enable_sounds": "Alert Sounds",
        "field_strategy_prompt": "Strategy Instructions (Prompt)",
        "field_rag_directory": "Knowledge Folder (RAG)",
        "field_lang_response": "Response Language (AI)",
        "field_enable_rag": "Use of RAG / Training",
        "sounds_enabled": "🔊 Enabled",
        "sounds_disabled": "🔇 Disabled",
        "rag_enabled": "✅ Enabled",
        "rag_disabled": "❌ Disabled",
        "market_forex": "🌐 Forex",
        "market_indices": "📊 Indices",
        "market_commodities": "🥇 Commodities",
        "market_crypto": "₿ Crypto",
        "market_acciones": "🏢 Stocks",
        "chart_candles": "🕯️ Candles",
        "chart_line": "📈 Line",
        "chart_bars": "📊 Bars",
        
        "balance_reset_success": "Balance reset successfully",
        "history_cleared_success": "History deleted",
        "export_success": "History exported successfully",
        "export_error": "Error exporting",
        "connection_error": "Connection error",

        # Step 5: AI Provider
        "step5_title": "Artificial Intelligence",
        "step5_header": "AI Provider",
        "field_ai_provider": "AI Provider",
        "field_ai_api_key": "API Key",
        "field_ai_model": "Model",
        "field_ai_endpoint": "Endpoint (URL)",
        "field_ai_api_version": "API Version",
        "btn_test_connection": "Test Connection",
        "test_success": "✅ Connection successful",
        "test_fail": "❌ Connection error",
        "testing": "Testing...",
        "ai_key_placeholder": "sk-... or your API Key",
        "ai_endpoint_placeholder": "https://your-resource.openai.azure.com/...",
        
        "trading_mode_label": "Trading Mode",
        "mode_simulation": "🎮 Simulation",
        "mode_real": "💰 Real Account",
        "real_mode_warning": "⚠️ Trading in real mode carries high risk of capital loss",
        "field_lot_size": "Volume (Lots)",
        "field_sl_multiplier": "SL (ATR ×)",
        "field_tp_ratio": "TP Ratio (R:R)",
        "equity_label": "Real Equity",
        "real_balance": "Real Balance",
        "market_open": "Market Open",
        "market_closed": "Market Closed",
        "next_analysis_in": "Next analysis in",
        "next_analysis": "Next analysis",
        "analyzing": "Analyzing...",
    },
    "pt": {
        "app_title": "TraderExpert",
        "start": "Iniciar",
        "pause": "Pausar",
        "stop": "Parar",
        "analyze": "Analisar",
        "settings": "Configurações",
        "virtual_balance": "Saldo Virtual",
        "active_asset": "Ativo",
        "wins": "Ganhas",
        "losses": "Perdidas",
        "confidence": "Confiança",
        "engine_state": "Estado do Motor",
        "risks_detected": "Riscos Detectados",
        "external_context": "Contexto Externo",
        "date": "Data",
        "asset": "Ativo",
        "signal": "Sinal",
        "status": "Estado",
        "conf": "Conf.",
        "reason": "Razão da Análise",
        "delta": "Delta",
        "page_info": "Página {page} de {total}",
        "no_signals": "Sem sinais registrados",
        "no_signals_desc": "Os sinais aparecerão aqui automaticamente assim que você iniciar a análise de mercado.",
        "confirm_title": "Confirmar",
        "confirm_text": "Tem certeza de que deseja realizar esta ação?",
        "cancel": "Cancelar",
        "confirm": "Confirmar",
        "reset_balance_tip": "Redefinir saldo virtual",
        "clear_history_tip": "Limpar histórico de sinais",
        "export_csv_tip": "Exportar histórico para CSV",
        "mt5_connected": "Conectado",
        "mt5_disconnected": "Desconectado",
        "scanning": "Escaneando mercado...",
        "scanning_btn": "ESCANEAR...",
        "state_running": "Ativo",
        "state_stopped": "Parado",
        "dir_wait": "ESPERAR",
        "dir_up": "SOBE",
        "dir_down": "CAI",
        "no_risks": "Nenhum risco detectado.",
        "no_news": "Nenhuma notícia relevante no momento.",
        "waiting_login": "Aguardando login.",
        "mt5_not_connected": "MetaTrader 5 não conectado.",
        "analysis_in_progress": "Análise em andamento...",
        "reset_balance_confirm_text": "Tem certeza de que deseja redefinir o saldo virtual ao valor inicial?",
        "clear_history_confirm_text": "Tem certeza de que deseja excluir permanentemente todo o histórico de sinais?",
        "minimize_aria": "Minimizar",
        "fullscreen_aria": "Tela Cheia",
        "quit_aria": "Sair",
        "entry_label": "Entrada",
        "exit_label": "Saída",
        "sources_connected_format": "{0} fontes conectadas",
        "news_processed_format": "{1} eventos/notícias processados",
        "seeking_market_events": "Buscando eventos de mercado...",
        
        # Settings page specific
        "step1_title": "Conexão",
        "step2_title": "Mercado",
        "step3_title": "Simulação",
        "step4_title": "Estrategia",
        "config_title": "Configurações do TraderExpert",
        "save": "Salvar Configurações",
        "next": "Avançar",
        "prev": "Voltar",
        "back_home": "Voltar ao Início",
        "step1_header": "Terminal MT5",
        "step2_header": "Configuração do Mercado",
        "step3_header": "Parámetros e Som",
        "step4_header": "Estratégia e Inteligência (RAG)",
        "field_mt5_path": "Caminho do terminal64.exe",
        "field_mt5_account": "Conta",
        "field_mt5_password": "Senha",
        "field_mt5_server": "Servidor",
        "field_market_type": "Tipo de mercado",
        "field_active_symbol": "Ativo (Símbolo)",
        "field_timeframe": "Temporalidad",
        "field_chart_type": "Tipo de Gráfico",
        "field_virtual_balance": "Capital Virtual",
        "field_stake_amount": "Valor por Sinal",
        "field_payout_percent": "Payout %",
        "field_confidence_threshold": "Confiança Mínima",
        "field_prediction_horizon": "Horizonte de Previsão (min)",
        "field_analysis_interval": "Intervalo de Análise (min)",
        "field_enable_sounds": "Sons de Alerta",
        "field_strategy_prompt": "Instruções de Estratégia (Prompt)",
        "field_rag_directory": "Pasta de Conhecimento (RAG)",
        "field_lang_response": "Idioma de la App",
        "field_enable_rag": "Uso de RAG / Treinamento",
        "sounds_enabled": "🔊 Ativado",
        "sounds_disabled": "🔇 Desactivado",
        "rag_enabled": "✅ Ativado",
        "rag_disabled": "❌ Desactivado",
        "market_forex": "🌐 Forex",
        "market_indices": "📊 Índices",
        "market_commodities": "🥇 Commodities",
        "market_crypto": "₿ Cripto",
        "market_acciones": "🏢 Ações",
        "chart_candles": "🕯️ Velas",
        "chart_line": "📈 Linha",
        "chart_bars": "📊 Barras",
        
        "balance_reset_success": "Saldo redefinido com sucesso",
        "history_cleared_success": "Histórico excluído",
        "export_success": "Histórico exportado com sucesso",
        "export_error": "Erro ao exportar",
        "connection_error": "Erro de conexão",

        # Step 5: AI Provider
        "step5_title": "Inteligência Artificial",
        "step5_header": "Provedor de IA",
        "field_ai_provider": "Provedor de IA",
        "field_ai_api_key": "Chave API",
        "field_ai_model": "Modelo",
        "field_ai_endpoint": "Endpoint (URL)",
        "field_ai_api_version": "Versão da API",
        "btn_test_connection": "Testar Conexão",
        "test_success": "✅ Conexão bem-sucedida",
        "test_fail": "❌ Erro de conexão",
        "testing": "Testando...",
        "ai_key_placeholder": "sk-... ou sua Chave API",
        "ai_endpoint_placeholder": "https://seu-recurso.openai.azure.com/...",
        
        "trading_mode_label": "Modo de Operação",
        "mode_simulation": "🎮 Simulação",
        "mode_real": "💰 Conta Real",
        "real_mode_warning": "⚠️ Operar no modo real envolve risco de perda de capital",
        "field_lot_size": "Volume (Lotes)",
        "field_sl_multiplier": "SL (ATR ×)",
        "field_tp_ratio": "TP Ratio (R:R)",
        "equity_label": "Patrimônio Real",
        "real_balance": "Saldo Real",
        "market_open": "Mercado Aberto",
        "market_closed": "Mercado Fechado",
        "next_analysis_in": "Próxima análise em",
        "next_analysis": "Próxima análise",
        "analyzing": "Analisando...",
    },
    "fr": {
        "app_title": "TraderExpert",
        "start": "Démarrer",
        "pause": "Pause",
        "stop": "Arrêter",
        "analyze": "Analyser",
        "settings": "Paramètres",
        "virtual_balance": "Solde Virtuel",
        "active_asset": "Actif",
        "wins": "Gagnées",
        "losses": "Perdues",
        "confidence": "Confiance",
        "engine_state": "État du Moteur",
        "risks_detected": "Risques Détectés",
        "external_context": "Contexte Externe",
        "date": "Date",
        "asset": "Actif",
        "signal": "Signal",
        "status": "Statut",
        "conf": "Conf.",
        "reason": "Raison de l'Analyse",
        "delta": "Delta",
        "page_info": "Page {page} sur {total}",
        "no_signals": "Aucun signal enregistré",
        "no_signals_desc": "Les signaux apparaîtront ici automatiquement une fois que vous aurez lancé l'analyse du marché.",
        "confirm_title": "Confirmer",
        "confirm_text": "Êtes-vous sûr de vouloir effectuer cette action ?",
        "cancel": "Annuler",
        "confirm": "Confirmer",
        "reset_balance_tip": "Réinitialiser le solde virtuel",
        "clear_history_tip": "Effacer l'historique des signaux",
        "export_csv_tip": "Exporter l'historique au format CSV",
        "mt5_connected": "Connecté",
        "mt5_disconnected": "Déconnécte",
        "scanning": "Scan du marché...",
        "scanning_btn": "ANALYSE...",
        "state_running": "Actif",
        "state_stopped": "Arrêté",
        "dir_wait": "ATTENDRE",
        "dir_up": "HAUSSE",
        "dir_down": "BAISSE",
        "no_risks": "Aucun risque détecté.",
        "no_news": "Aucune actualité pertinente pour le moment.",
        "waiting_login": "En attente de connexion.",
        "mt5_not_connected": "MetaTrader 5 non connecté.",
        "analysis_in_progress": "Analyse en cours...",
        "reset_balance_confirm_text": "Êtes-vous sûr de vouloir réinitialiser le solde virtuel à sa valeur initiale ?",
        "clear_history_confirm_text": "Êtes-vous sûr de vouloir supprimer définitivement tout l'historique des signaux ?",
        "minimize_aria": "Minimiser",
        "fullscreen_aria": "Plein Écran",
        "quit_aria": "Quitter",
        "entry_label": "Entrée",
        "exit_label": "Sortie",
        "sources_connected_format": "{0} sources connectées",
        "news_processed_format": "{1} événements/nouvelles traités",
        "seeking_market_events": "Recherche d'événements de marché...",
        
        # Settings page specific
        "step1_title": "Connexion",
        "step2_title": "Marché",
        "step3_title": "Simulation",
        "step4_title": "Stratégie",
        "config_title": "Paramètres de TraderExpert",
        "save": "Enregistrer",
        "next": "Suivant",
        "prev": "Précédent",
        "back_home": "Retour à l'Accueil",
        "step1_header": "Terminal MT5",
        "step2_header": "Configuration du Marché",
        "step3_header": "Paramètres et Son",
        "step4_header": "Stratégie et Intelligence (RAG)",
        "field_mt5_path": "Chemin de terminal64.exe",
        "field_mt5_account": "Compte",
        "field_mt5_password": "Mot de passe",
        "field_mt5_server": "Serveur",
        "field_market_type": "Type de marché",
        "field_active_symbol": "Actif (Symbole)",
        "field_timeframe": "Temporalité",
        "field_chart_type": "Type de graphique",
        "field_virtual_balance": "Capital virtuel",
        "field_stake_amount": "Montant par signal",
        "field_payout_percent": "Payout %",
        "field_confidence_threshold": "Confiance minimale",
        "field_prediction_horizon": "Horizon de prédiction (min)",
        "field_analysis_interval": "Intervalle d'analyse (min)",
        "field_enable_sounds": "Sons d'alerte",
        "field_strategy_prompt": "Instructions de stratégie (Prompt)",
        "field_rag_directory": "Dossier de connaissances (RAG)",
        "field_lang_response": "Langue de réponse (IA)",
        "field_enable_rag": "Utilisation de RAG / Entraînement",
        "sounds_enabled": "🔊 Activé",
        "sounds_disabled": "🔇 Désactivé",
        "rag_enabled": "✅ Activé",
        "rag_disabled": "❌ Désactivé",
        "market_forex": "🌐 Forex",
        "market_indices": "📊 Indices",
        "market_commodities": "🥇 Matières Premières",
        "market_crypto": "₿ Crypto",
        "market_acciones": "🏢 Actions",
        "chart_candles": "🕯️ Bougies",
        "chart_line": "📈 Ligne",
        "chart_bars": "📊 Barres",
        
        "balance_reset_success": "Solde réinitialisé avec succès",
        "history_cleared_success": "Historique supprimé",
        "export_success": "Historique exporté avec succès",
        "export_error": "Erreur lors de l'exportation",
        "connection_error": "Erreur de connexion",

        # Step 5: AI Provider
        "step5_title": "Intelligence Artificielle",
        "step5_header": "Fournisseur d'IA",
        "field_ai_provider": "Fournisseur d'IA",
        "field_ai_api_key": "Clé API",
        "field_ai_model": "Modèle",
        "field_ai_endpoint": "Point de terminaison (URL)",
        "field_ai_api_version": "Version API",
        "btn_test_connection": "Tester la Connexion",
        "test_success": "✅ Connexion réussie",
        "test_fail": "❌ Erreur de connexion",
        "testing": "Test en cours...",
        "ai_key_placeholder": "sk-... ou votre Clé API",
        "ai_endpoint_placeholder": "https://votre-ressource.openai.azure.com/...",
        
        "trading_mode_label": "Mode de Trading",
        "mode_simulation": "🎮 Simulation",
        "mode_real": "💰 Compte Réel",
        "real_mode_warning": "⚠️ Le trading en mode réel comporte un risque de perte de capital",
        "field_lot_size": "Volume (Lots)",
        "field_sl_multiplier": "SL (ATR ×)",
        "field_tp_ratio": "Rapport TP (R:R)",
        "equity_label": "Fonds Propres",
        "real_balance": "Solde Réel",
        "market_open": "Marché Ouvert",
        "market_closed": "Marché Fermé",
        "next_analysis_in": "Prochaine analyse dans",
        "next_analysis": "Prochaine analyse",
        "analyzing": "Analyse en cours...",
    },
    "de": {
        "app_title": "TraderExpert",
        "start": "Starten",
        "pause": "Pausieren",
        "stop": "Stoppen",
        "analyze": "Analysieren",
        "settings": "Einstellungen",
        "virtual_balance": "Virtuelles Guthaben",
        "active_asset": "Wert",
        "wins": "Gewonnen",
        "losses": "Verloren",
        "confidence": "Vertrauen",
        "engine_state": "Motorstatus",
        "risks_detected": "Erkannte Risiken",
        "external_context": "Externer Kontext",
        "date": "Datum",
        "asset": "Wert",
        "signal": "Signal",
        "status": "Status",
        "conf": "Vertr.",
        "reason": "Analyse-Grund",
        "delta": "Delta",
        "page_info": "Seite {page} von {total}",
        "no_signals": "Keine Signale registriert",
        "no_signals_desc": "Signale werden hier automatisch angezeigt, sobald Sie mit der Marktanalyse beginnen.",
        "confirm_title": "Bestätigen",
        "confirm_text": "Sind Sie sicher, dass Sie diese Aktion ausführen möchten?",
        "cancel": "Abbrechen",
        "confirm": "Bestätigen",
        "reset_balance_tip": "Virtuelles Guthaben zurücksetzen",
        "clear_history_tip": "Signalverlauf löschen",
        "export_csv_tip": "Verlauf in CSV exportieren",
        "mt5_connected": "Verbunden",
        "mt5_disconnected": "Getrennt",
        "scanning": "Markt scannen...",
        "scanning_btn": "ANALYSE...",
        "state_running": "Aktiv",
        "state_stopped": "Gestoppt",
        "dir_wait": "WARTEN",
        "dir_up": "ANSTIEG",
        "dir_down": "ABSTURZ",
        "no_risks": "Keine Risiken erkannt.",
        "no_news": "Aktuell keine relevanten Nachrichten vorhanden.",
        "waiting_login": "Warten auf Anmeldung.",
        "mt5_not_connected": "MetaTrader 5 nicht verbunden.",
        "analysis_in_progress": "Analyse läuft...",
        "reset_balance_confirm_text": "Sind Sie sicher, dass Sie das virtuelle Guthaben auf den Anfangswert zurücksetzen möchten?",
        "clear_history_confirm_text": "Sind Sie sicher, dass Sie den gesamten Signalverlauf dauerhaft löschen möchten?",
        "minimize_aria": "Minimieren",
        "fullscreen_aria": "Vollbild",
        "quit_aria": "Beenden",
        "entry_label": "Einstieg",
        "exit_label": "Ausstieg",
        "sources_connected_format": "{0} verbundene Quellen",
        "news_processed_format": "{1} Ereignisse/Nachrichten verarbeitet",
        "seeking_market_events": "Marktereignisse suchen...",
        
        # Settings page specific
        "step1_title": "Verbindung",
        "step2_title": "Markt",
        "step3_title": "Simulation",
        "step4_title": "Strategie",
        "config_title": "TraderExpert Einstellungen",
        "save": "Speichern",
        "next": "Weiter",
        "prev": "Zurück",
        "back_home": "Zurück zum Start",
        "step1_header": "Terminal MT5",
        "step2_header": "Markteinstellungen",
        "step3_header": "Parameter & Ton",
        "step4_header": "Strategie & RAG-Wissen",
        "field_mt5_path": "Pfad zur terminal64.exe",
        "field_mt5_account": "Kontonummer",
        "field_mt5_password": "Kennwort",
        "field_mt5_server": "Broker-Server",
        "field_market_type": "Markttyp",
        "field_active_symbol": "Wert (Symbol)",
        "field_timeframe": "Temporalität",
        "field_chart_type": "Diagrammtyp",
        "field_virtual_balance": "Virtuelles Kapital",
        "field_stake_amount": "Betrag pro Signal",
        "field_payout_percent": "Payout %",
        "field_confidence_threshold": "Min. Vertrauen",
        "field_prediction_horizon": "Prognosehorizont (min)",
        "field_analysis_interval": "Analyseintervall (min)",
        "field_enable_sounds": "Warnsignale",
        "field_strategy_prompt": "Strategie-Anweisungen (Prompt)",
        "field_rag_directory": "Wissensordner (RAG)",
        "field_lang_response": "Antwortsprache (KI)",
        "field_enable_rag": "RAG-Nutzung / Training",
        "sounds_enabled": "🔊 Aktiviert",
        "sounds_disabled": "🔇 Deaktiviert",
        "rag_enabled": "✅ Aktiviert",
        "rag_disabled": "❌ Deaktiviert",
        "market_forex": "🌐 Forex",
        "market_indices": "📊 Indizes",
        "market_commodities": "🥇 Rohstoffe",
        "market_crypto": "₿ Krypto",
        "market_acciones": "🏢 Aktien",
        "chart_candles": "🕯️ Kerzen",
        "chart_line": "📈 Linie",
        "chart_bars": "📊 Balken",
        
        "balance_reset_success": "Guthaben erfolgreich zurückgesetzt",
        "history_cleared_success": "Verlauf gelöscht",
        "export_success": "Verlauf erfolgreich exportiert",
        "export_error": "Fehler beim Exportieren",
        "connection_error": "Verbindungsfehler",

        # Step 5: AI Provider
        "step5_title": "Künstliche Intelligenz",
        "step5_header": "KI-Anbieter",
        "field_ai_provider": "KI-Anbieter",
        "field_ai_api_key": "API-Schlüssel",
        "field_ai_model": "Modell",
        "field_ai_endpoint": "Endpunkt (URL)",
        "field_ai_api_version": "API-Version",
        "btn_test_connection": "Verbindung testen",
        "test_success": "✅ Verbindung erfolgreich",
        "test_fail": "❌ Verbindungsfehler",
        "testing": "Teste...",
        "ai_key_placeholder": "sk-... oder Ihr API-Schlüssel",
        "ai_endpoint_placeholder": "https://ihre-ressource.openai.azure.com/...",
        
        "trading_mode_label": "Handelsmodus",
        "mode_simulation": "🎮 Simulation",
        "mode_real": "💰 Reales Konto",
        "real_mode_warning": "⚠️ Der Handel im Echtgeldmodus birgt das Risiko von Kapitalverlusten",
        "field_lot_size": "Volumen (Lots)",
        "field_sl_multiplier": "SL (ATR ×)",
        "field_tp_ratio": "TP-Verhältnis (R:R)",
        "equity_label": "Reales Eigenkapital",
        "real_balance": "Realer Kontostand",
        "market_open": "Markt Geöffnet",
        "market_closed": "Markt Geschlossen",
        "next_analysis_in": "Nächste Analyse in",
        "next_analysis": "Nächste Analyse",
        "analyzing": "Analysieren...",
    }
}
